export default {
	/*Filter:(name)=>{ this[name] = SP_SELECTPRODUCTINVENTORY.data.length>0? SP_SELECTPRODUCTINVENTORY.data[0][name]!==null?SP_SELECTPRODUCTINVENTORY.data[0][name]:"" :""}
	,INVENTORY_ID:{set:this.Filter("INVENTORY_ID"),data:""}
	,PRODUCT_ID:this.Filter(SP_SELECTPRODUCTINVENTORY.data[0].PRODUCT_ID  )
	,INVENTORY_NAME:this.Filter()//this.Filter(SP_SELECTPRODUCTINVENTORY.data[0].INVENTORY_NAME  )===undefined?"":this.Filter(SP_SELECTPRODUCTINVENTORY.data[0].INVENTORY_NAME  )
 //,PRODUCT_NAME_EN :this.Filter(SP_SELECTPRODUCTINVENTORY.data[0]  )
 //,PRODUCT_NAME_TH :this.Filter(SP_SELECTPRODUCTINVENTORY.data[0]  )
 //,PRODUCT_TYPE_EN :this.Filter(SP_SELECTPRODUCTINVENTORY.data[0]  )
 //,PRODUCT_TYPE_TH :this.Filter(SP_SELECTPRODUCTINVENTORY.data[0]  )
 ,METER_ID :this.Filter(SP_SELECTPRODUCTINVENTORY.data[0].METER_ID  )
 ,FLOOR_NO :this.Filter(SP_SELECTPRODUCTINVENTORY.data[0].FLOOR_NO  )
 ,PRODUCT_DESCRIPTION :this.Filter(SP_SELECTPRODUCTINVENTORY.data[0].PRODUCT_DESCRIPTION  )
 ,ZONE :this.Filter(SP_SELECTPRODUCTINVENTORY.data[0].ZONE  )
 ,ROFR_STATUS :this.Filter(SP_SELECTPRODUCTINVENTORY.data[0].ROFR_STATUS  )
 ,ROFR_FRONT :this.Filter(SP_SELECTPRODUCTINVENTORY.data[0].ROFR_FRONT  )
 ,ROFR_BACK :this.Filter(SP_SELECTPRODUCTINVENTORY.data[0].ROFR_BACK  )
 ,ROFR_LEFT :this.Filter(SP_SELECTPRODUCTINVENTORY.data[0].ROFR_LEFT  )
 ,ROFR_RIGHT :this.Filter(SP_SELECTPRODUCTINVENTORY.data[0].ROFR_RIGHT  )
 ,UNIT :this.Filter(SP_SELECTPRODUCTINVENTORY.data[0].UNIT  )
 //,CT_SIZE1:
 //,CT_SIZE2:
 ,CT :this.Filter(SP_SELECTPRODUCTINVENTORY.data[0].CT  )
 ,START_UNIT :this.Filter(SP_SELECTPRODUCTINVENTORY.data[0].START_UNIT  )
 //,METER_VALUE_LINE_NUMBER:NULL
 ,DIGIT_LENGTH :this.Filter(SP_SELECTPRODUCTINVENTORY.data[0].DIGIT_LENGTH  )
 ,DECIMAL_POINT :this.Filter(SP_SELECTPRODUCTINVENTORY.data[0].DECIMAL_POINT  )
 //,MINIMUM_UNIT:NULL
 //,MAXIMUM_UNIT:NULL
 //,AVERAGE_UNIT:NULL
 //,TOTAL_MONTH:NULL
 //,TOTAL_VALUE:NULL
 ,PRICE_PER_UNIT :this.Filter(SP_SELECTPRODUCTINVENTORY.data[0].PRICE_PER_UNIT  )
 //,TOTAL_PRICE:NULL
 ,START_DATE :moment(this.Filter(SP_SELECTPRODUCTINVENTORY.data[0].START_DATE  )).format()
 ,END_DATE :moment(this.Filter(SP_SELECTPRODUCTINVENTORY.data[0].END_DATE  )).format()
 ,STATUS :this.Filter(SP_SELECTPRODUCTINVENTORY.data[0].STATUS  )
 //,ACTIVE:true
 //,CREATE_DATE:1727789939573
 //,UPDATE_DATE:NULL
 //,USER_ID:NULL*/
}